//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SampleForumSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SampleForumSource { }
#else

	public class SampleForumSource : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public SampleForumSource()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/Awful.WP7.Controls;component/SampleData/SampleForumSource/SampleForumSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private Forums _Forums = new Forums();

		public Forums Forums
		{
			get
			{
				return this._Forums;
			}
		}
	}

	public class ForumsItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Title = string.Empty;

		public string Title
		{
			get
			{
				return this._Title;
			}

			set
			{
				if (this._Title != value)
				{
					this._Title = value;
					this.OnPropertyChanged("Title");
				}
			}
		}

		private string _Nickname = string.Empty;

		public string Nickname
		{
			get
			{
				return this._Nickname;
			}

			set
			{
				if (this._Nickname != value)
				{
					this._Nickname = value;
					this.OnPropertyChanged("Nickname");
				}
			}
		}

		private System.Windows.Media.ImageSource _Image = null;

		public System.Windows.Media.ImageSource Image
		{
			get
			{
				return this._Image;
			}

			set
			{
				if (this._Image != value)
				{
					this._Image = value;
					this.OnPropertyChanged("Image");
				}
			}
		}

		private string _PrimaryColor = string.Empty;

		public string PrimaryColor
		{
			get
			{
				return this._PrimaryColor;
			}

			set
			{
				if (this._PrimaryColor != value)
				{
					this._PrimaryColor = value;
					this.OnPropertyChanged("PrimaryColor");
				}
			}
		}

		private string _SecondaryColor = string.Empty;

		public string SecondaryColor
		{
			get
			{
				return this._SecondaryColor;
			}

			set
			{
				if (this._SecondaryColor != value)
				{
					this._SecondaryColor = value;
					this.OnPropertyChanged("SecondaryColor");
				}
			}
		}
	}

	public class Forums : System.Collections.ObjectModel.ObservableCollection<ForumsItem>
	{ 
	}
#endif
}
