//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Awful.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Awful.Common.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www/awful.js.
        /// </summary>
        internal static string FILE_PATH_AWFUL_JAVASCRIPT {
            get {
                return ResourceManager.GetString("FILE_PATH_AWFUL_JAVASCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www/awful.css.
        /// </summary>
        internal static string FILE_PATH_CSS {
            get {
                return ResourceManager.GetString("FILE_PATH_CSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to currentThread.xml.
        /// </summary>
        internal static string FILE_PATH_CURRENT_THREAD {
            get {
                return ResourceManager.GetString("FILE_PATH_CURRENT_THREAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forums.xml.
        /// </summary>
        internal static string FILE_PATH_FORUMS_LIST {
            get {
                return ResourceManager.GetString("FILE_PATH_FORUMS_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www/jquery.min.js.
        /// </summary>
        internal static string FILE_PATH_JQUERY_JAVASCRIPT {
            get {
                return ResourceManager.GetString("FILE_PATH_JQUERY_JAVASCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www/view.html.
        /// </summary>
        internal static string FILE_PATH_WWW {
            get {
                return ResourceManager.GetString("FILE_PATH_WWW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Awful;component/www/awful.js.
        /// </summary>
        internal static string RESOURCE_PATH_AWFUL_JAVASCRIPT {
            get {
                return ResourceManager.GetString("RESOURCE_PATH_AWFUL_JAVASCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Awful;component/www/main.css.
        /// </summary>
        internal static string RESOURCE_PATH_CSS {
            get {
                return ResourceManager.GetString("RESOURCE_PATH_CSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Awful;component/www/jquery.min.js.
        /// </summary>
        internal static string RESOURCE_PATH_JQUERY {
            get {
                return ResourceManager.GetString("RESOURCE_PATH_JQUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Awful;component/www/view.html.
        /// </summary>
        internal static string RESOURCE_PATH_THREADVIEW {
            get {
                return ResourceManager.GetString("RESOURCE_PATH_THREADVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentThread.
        /// </summary>
        internal static string STATE_CURRENT_THREAD_KEY {
            get {
                return ResourceManager.GetString("STATE_CURRENT_THREAD_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForumCache.
        /// </summary>
        internal static string STATE_FORUM_CACHE_KEY {
            get {
                return ResourceManager.GetString("STATE_FORUM_CACHE_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string THREAD_DEFAULT_ITEM_OPACITY {
            get {
                return ResourceManager.GetString("THREAD_DEFAULT_ITEM_OPACITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.2.
        /// </summary>
        internal static string THREAD_VIEWED_ITEM_OPACITY {
            get {
                return ResourceManager.GetString("THREAD_VIEWED_ITEM_OPACITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view.html.
        /// </summary>
        internal static string THREAD_VIEWER_FILENAME {
            get {
                return ResourceManager.GetString("THREAD_VIEWER_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.
        /// </summary>
        internal static string THREAD_VIEWER_WEB_FOLDER {
            get {
                return ResourceManager.GetString("THREAD_VIEWER_WEB_FOLDER", resourceCulture);
            }
        }
    }
}
